# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link_01
  pid: {p: 2000.0, i: 100, d: 500.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_01__link_02 
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_01__link_02_A
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_02__link_03
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_02_A__link_03_A
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_03__link_04
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_03_A__link_04_A
  pid: {p: 50000.0, i: 100, d: 2000.0}
